# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

trigger:
- master

variables:
  imageName: 'jannemattila/xoblazor:$(Build.BuildNumber)'
  BuildConfiguration: 'Release'

name: 1.0.$(Rev:r)
steps:
- task: DotNetCoreInstaller@0
  displayName: 'Install .NET Core SDK'
  inputs:
    version: '3.0.100-preview6-012264'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false
    modifyOutputPath: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: app'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/XO.Web/dist/'
    ArtifactName: app

#- task: Docker@1
#  displayName: 'Build an image'
#  inputs:
#    imageName: $(imageName)
#    includeLatestTag: true
#- task: Docker@1
#  displayName: 'Push an image'
#  inputs:
#    containerregistrytype: 'Container Registry'
#    dockerRegistryEndpoint: DockerHub
#    command: 'Push an image'
#    imageName: $(imageName)
#    includeLatestTag: true
#